baseURL = "https://ashishkhuraishy.github.io/blog/"
languageCode = "en-us"
title = "Ashish's Blog"
theme="archie"
copyright = "© Ashish"
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
mode="dark" # color-mode → light,dark,toggle or auto
useCDN=true # don't use CDNs for fonts and icons, instead serve them locally.
subtitle = "Random Thoughts And Technical Content"

# Social Tags
[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/ashishkhuraishy"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/ashishkhuraishy/"

[[params.social]]
name = "Email"
icon = "mail"
url = "mailto:ashishkhuraishy@gmail.com"

# Main menu Items
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3